spring:
  application:
    name: distributed-rate-limiter
  redis:
    host: localhost
    port: 6379

server:
  port:
    8081

rate-limiter:
  api-key:
    capacity: 10
    refill-tokens: 10
    refill-duration-millis: 60000