spring:
  application:
    name: distributed-rate-limiter
  redis:
    host: localhost
    port: 6379

server:
  port:
    8081

rate-limiter:
  api-key:
    capacity: 1000
    refill-tokens: 1000
    refill-duration-millis: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true